import Head from 'next/head'
import HeroSection from '../components/HeroSection'
import CarSection from '../components/CarSection'
import JokerSection from '../components/JokerSection'
import PheonixSection from '../components/PheonixSection'
import ThankYouSection from '../components/ThankYouSection'

export default function Home() {
  return (
    <div>
      <Head>
        <title>3D Models</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <div>
          <HeroSection/>
          <CarSection/>
          <JokerSection/>
          <PheonixSection/>
          <ThankYouSection/>
        </div>
      </body>
     

    </div>
  )
}
